### ISSUE TITLE
`Cannot read property 'toLowerCase' of undefined` error when viewing templated HTML file

### ISSUE THREAD

**Issue by mihaip** [patrys/vscode-code-outline#25]
When loading a .html file with some custom template directives, a "`Cannot read property 'toLowerCase' of undefined" error message appears. The stack in the VSCode dev tools is:

```
Cannot read property 'toLowerCase' of undefined: TypeError: Cannot read property 'toLowerCase' of undefined
    at SymbolNode.compareSymbols (.../patrys.vscode-code-outline-0.0.7/out/src/symbolOutline.js:42:26)
    at Array.sort (native)
    at SymbolNode.sort (.../patrys.vscode-code-outline-0.0.7/out/src/symbolOutline.js:48:23)
    at SymbolOutlineProvider.<anonymous> (.../patrys.vscode-code-outline-0.0.7/out/src/symbolOutline.js:101:22)
    at Generator.next (<anonymous>)
    at fulfilled (.../patrys.vscode-code-outline-0.0.7/out/src/symbolOutline.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

The minimal repro for this is this HTML file:

```
<% import foo %>

<html>
</html>
```

**Comment by piyushkmr** [comment]
I am facing the same issue in vscode

**Comment by patrys** [comment]
It would help if you could provide a minimal (ie. ideally a couple lines long) example file to reproduce this.

**Comment by mihaip** [comment]
@patrys: I did, see "The minimal repro for this is this HTML file" in my initial comment.

**Comment by patrys** [comment]
@mihaip I am unable to reproduce this. Are you using any extensions that handle HTML files in a non-standard way? With the built-in HTML syntax I get an empty node for every `<% foo %>` (which matches the Symbol Provider's behavior) but no exception.

**Comment by patrys** [comment]
I'm going to close this since I can't reproduce this problem.
